<?php

/**
 * Implementation of hook_menu().
 */
function bcc_menu() {
  $items = array();

  // Admin page.
  $items['admin/settings/bcc'] = array(
    'title' => 'CCC BCC Settings',
    'description' => 'Change configuration for BCC',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bcc_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function bcc_admin_settings() {

  $form['bcc'] = array(
    '#type' => 'fieldset',
    '#title' => '',
    '#description' => t('Configure Blind Carbon Copy settings.'),
  );
  $form['bcc']['bcc_mail'] = array(
    '#type' => 'radios',
    '#title' => 'Blind Carbon Copy',
    '#description' => t('Choose whether you want the site to automatically BCC all email its sends'),
    '#options' => array(
      0 => 'Do not send BCC',
      1 => 'Send BCC',
    ),
    '#default_value' => variable_get('bcc_mail', 0),
  );
  $form['bcc']['bcc_mail_address'] = array(
    '#type' => 'textfield',
    '#title' => 'BCC address',
    '#description' => t('Enter a valid email address that should receive a blind carbon copy (bcc) of all email sent by the site.'),
    '#default_value' => variable_get('bcc_mail_address', variable_get('site_mail', '')),
  );

  $form['#validate'][] = 'bcc_admin_settings_validate';

  return system_settings_form($form);
}

/**
 * Validate the system settings form.
 */
function bcc_admin_settings_validate(&$form, $form_state) {
  if ($form_state['values']['bcc']['bcc_mail']) {
    if (!drupal_valid_email($form_state['values']['bcc']['bcc_mail_address'])) {
      form_set_error('bcc][bcc_mail_address', t('Please enter a valid email address'));
    }
  }
}

/**
 * Implementation of hook_mail_alter()
 */
function bcc_mail_alter(&$message) {
  if (variable_get('bcc_mail', 0)) {
    $message['headers']['Bcc'] = variable_get('bcc_mail_address', variable_get('site_mail', ''));
  }
}
