<?php

/**
 * Form alter for the logintoboggan signup form.
 */
function register_form_alter(&$form, $form_state, $form_id) {
  if($form_id == 'user_register') {
    $form['name']['#type'] = 'hidden';
    $form['name']['#required'] = FALSE;
    $form['#validate'][] = 'register_user_register_validate';
  }
}

/**
 * Validation function override.
 */
function register_user_register_validate($form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
  $form_state['clicked_button']['#post']['name'] = $form_state['values']['mail'];
}
