<?php

/**
 * Form alter for the logintoboggan signup form.
 *
 * Because we login via the email address only, hide the username field.
 */
function overrides_form_alter(&$form, $form_state, $form_id) {
  if($form_id == 'user_register') {
    $form['name']['#type'] = 'hidden';
    $form['name']['#required'] = FALSE;
    $form['#validate'][] = 'register_user_register_validate';
  }
}

/**
 * User signup form validation function override.
 *
 * Because the username was blank, transpsoe the email address into the username field.
 */
function overrides_user_register_validate($form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
  $form_state['clicked_button']['#post']['name'] = $form_state['values']['mail'];
}

/**
 * Remove history section from the user profile.
 */
function overrides_user($type, &$edit, &$account, $category = NULL) {
  // remove history from user profile view
  if ($type == 'view') {
    unset($account->content['summary']);
  }
}
?>

/**
 * Titlecase function.
 */
function ccc_strtot($s) {
  $smallwordsarray = array( 'of','a','the','and','an','or','nor','but','is','if','then','else','when', 'at','from','by','on','off','for','in','out','over','to','into','with' );

  $words = explode(' ', $s);

  foreach($words as $key => $word) {
    if (!$key || !in_array($word, $smallwordsarray))
      $words[$key] = ucwords($word);
  }
  return implode(' ', $words);
}
