<?php

/**
 *
 * Handle registration info
 *
 * We are coupling a bit with uc_order. Using it's permission and
 * with an expectation that this module is installed.
 *
 * 'view all orders' is a placeholder admin
 * 'view own orders' is I've bought the tickets.
 */

/**
 * Implementation of hook_nodeapi()
 */
function register_nodeapi(&$node, $op) {
  if($node->type == 'timeslot' && $op == 'load') {
    $dateparts = split(' ', $node->title);
    $node->between = t('!start - !end', array('!start' => $dateparts[4], '!end' => $dateparts[6]));
  }
}

/**
 * Implementation of hook_menu().
 */
function register_menu() {
  $items = array();

  $items['admin/settings/register'] = array(
    'title' => 'CCC Registration Settings',
    'description' => 'Change configuration settings for Registration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('register_admin_settings'),
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/store/reports/custom/attendees'] = array(
    'title' => 'Attendee Registration Report',
    'description' => 'List all known attendees.',
    'page callback' => 'register_list_attendees',
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );


  $items['admin/store/reports/custom/presenters'] = array(
    'title' => 'Presenter Registration Report',
    'description' => 'List the registration status for presenters with accepted proposals.',
    'page callback' => 'register_list_presenter_payment_status',
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/store/reports/custom/coupons'] = array(
    'title' => 'Coupon usage list with names',
    'description' => 'List coupon usage',
    'page callback' => 'register_list_coupon_status',
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/store/reports/custom/overview'] = array(
    'title' => 'Registration Overview Report',
    'description' => 'List an overview of registration info.',
    'page callback' => 'register_list_overview',
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/tickets'] = array(
    'title' => 'Tickets',
    'description' => 'Conference ticket allocation',
    'page callback' => 'register_tickets',
    'page arguments' => array(1, 3),
    'access callback' => 'user_access',
    'access arguments' => array('view own orders'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['my-profile'] = array(
    'title' => 'My Profile',
    'page callback' => 'user_profile_goto',
    'access callback' => 'user_access',
    'access arguments' => array('edit own profile content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user-profile'] = array(
    'title' => 'Edit profile redirect',
    'page callback' => 'user_profile_redirect',
    'access callback' => 'user_access',
    'access arguments' => array('view own orders'),
    'type' => MENU_CALLBACK,
  );
  $items['register-thank-you'] = array(
    'title' => 'Thank you',
    'page callback' => 'register_thankyou',
    'access callback' => 'user_access',
    'access arguments' => array('view own orders'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/user/user/prizedraw'] = array(
    'title' => 'Prize Draw!',
    'description' => 'Select 10 random registrants for the prize draw.',
    'page callback' => 'register_prizedraw',
    'access callback' => 'user_access',
    'access arguments' => array('view all orders'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function register_admin_settings() {
  $form = array();
  $form['register_profile_blurb']['register_profile_nonreg_blurb'] = array(
    '#title' => 'Profile Blurb',
    '#description' => 'The text to show on a user profile when a user has not yet registered.',
    '#type' => 'textarea',
    '#default_value' => variable_get('register_profile_nonreg_blurb', '<p>You are not registered. !register.</p>'),
  );
  $form['register_profile_blurb']['register_no_allocations_blurb'] = array(
    '#title' => 'Allocations Blurb',
    '#description' => 'The text to show on the ticket allocations tab when a user has no tickets allocated to themselves.',
    '#type' => 'textarea',
    '#default_value' => variable_get('register_no_allocations_blurb', '<p>No tickets have been allocated to you. !register.</p>'),
  );
  $form['register_profile_blurb']['vars'] = array(
    '#type' => 'markup',
    '#value' => 'Available subsitution variables are !register, !fullconf, !tuesday, !wednesday, !thursday, !friday, dinner, !leadership',
  );

  // What does the 'Continue shopping' button say?
  $form['register_continue_shopping']['register_continue_shopping'] = array(
    '#title' => 'Continue Shopping',
    '#description' => 'The label to display on the Continue shopping button on a product page.',
    '#type' => 'textfield',
    '#default_value' => variable_get('register_continue_shopping', 'Continue shopping'),
  );

  return system_settings_form($form);
}

function user_profile_goto() {
  global $user;
  if ($user->uid) {
    drupal_goto('user/' . $user->uid . '/edit/profile' );
  }
  else {
    return drupal_access_denied();
  }
}

function user_profile_redirect($path1, $path2) {
  global $user;
  if ($user->uid) {
    drupal_goto('user/' . $user->uid . '/' . $path1 . '/' . $path2 );
  }
  else {
    return drupal_access_denied();
  }
}

/**
 * Implementation of hook_theme().
 */
function register_theme() {
  return array(
    'user_overview_registrations' => array(
      'arguments' => array('account' => NULL, $orders => NULL),
    ),
    'register_allocations_form_table' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * Implementation of hook_form_alter()
 */
function register_form_alter(&$form, $form_state, $form_id) {
  if($form_id == 'uc_order_view_update_form') {
    $form['order_assignee_listing'] = array(
      '#type' => 'fieldset',
      '#title' => 'Ticket assignments for this order',
      '#description' => 'List all users who have been assigned tickets from this order.',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['order_assignee_listing']['info'] = register_list_ticket_assignees($form['order_id']['#value']);
  }
}

/**
 * Helper that lists ticket assignees for a specific order id.
 * This order may contain multiple products, each with multiple assignees.
 */
function register_list_ticket_assignees($order_id) {
  $form = array();

  $order = uc_order_load($order_id);
  foreach($order->products as $product) {
    $form['order_product_' . $product->order_product_id] = array(
      '#type' => 'fieldset',
      '#title' => 'ID ' . $product->order_product_id . ' ' . $product->title,
      '#collapsible' => FALSE,
    );

    $data = array();
    $titles = array('First name', 'Surname', 'Position', 'Organisation', 'Email');
    $assignees = register_get_ticketholders($product);
    foreach($assignees as $assignee) {
      $profile = content_profile_load('profile', $assignee->uid);
      $data[] = array(
        $profile->field_profile_firstname[0]['value'],
        $profile->field_profile_surname[0]['value'],
        $profile->field_profile_position[0]['value'],
        $profile->field_profile_organisation[0]['value'],
        l($assignee->mail, 'user/' . $assignee->uid),
      );
    }

    $form['order_product_' . $product->order_product_id]['assignees'] = array(
      '#type' => 'markup',
      '#value' => theme('table', $titles, $data)
    );
  }
  return $form;
}

/**
 * Implementation of hook_user().
 */
function register_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  switch ($op) {
    case 'view':
      if($user->uid && (($user->uid == $account->uid && user_access('view own orders')) || user_access('view all orders'))) {

        // Get a big list of event purchases and stuff.
        $orders = register_get_orders($account->uid);

        foreach ($orders as $key => $order) {
          if (!$order->some_user_allocated && $order->qty == 1) {
            // No-one is allocated to this ticket, we could allocate them here.
            if (register_allocate_ticket($order->order_product_id, $account->uid)) {
              $order->tickets[$account->uid] = $account;
            }
          }
          // Other useful links:
          $order->manage_path = 'user/' . $account->uid . '/tickets/' . $order->order_product_id;
          // Assign modified data back to the array.
          $orders[$key] = $order;
        }

        $account->content['registrations'] = array(
          '#type' => 'user_profile_category',
          '#weight' => -6,
          '#title' => t('Conference registration'),
          'link' => array(
            '#type' => 'user_profile_item',
            '#value' => theme('user_overview_registrations', $account, $orders),
          ),
        );
      }

    case 'load':
      $orders = register_get_orders($account->uid);
      if ($orders) {
        $account->orders = $orders;
      }
      break;

    // This needs to only be active if the attendee role is required. It will
    // be magically set or disabled at login.
    //
    case 'login':
      register_toggle_attendee_role($account);
      break;
  }
}


function register_toggle_attendee_role(&$account) {

  // Check for allocated tickets.
  //
  $ticket = db_result(db_query("SELECT COUNT(order_product_id) FROM {ccc_ticket_allocation} WHERE uid=%d", $account->uid));

  // Attendee rid.
  //
  $rid = db_result(db_query("SELECT rid FROM {role} WHERE name = '%s'", 'attendee'));

  // Silently fail if no attendee role exists.
  //
  if (!$rid)
    return;

  // Work on a copy.
  //
  $victim = $account;

  // If a ticket is allocated to user but attendee role is NOT set ... add it.
  // If user has no ticket allocation but DOES have the attendee role set ... remove it.
  //
  if ($ticket && !in_array('attendee', $victim->roles)) {
    $roles = $victim->roles + array($rid => 'attendee');
    user_save($victim, array('roles' => $roles));
  }
  else if (!$ticket && in_array('attendee', $victim->roles)) {
    $roles = array_diff($victim->roles, array($rid => 'attendee'));
    user_save($victim, array('roles' => $roles));
  }

  // Overwrite the parameter account with the new details.
  //
  $account = $victim;
}

/**
 * This is the bit of information on the /user/% page.
 */
function theme_user_overview_registrations($account, $orders) {
  $output = '';
  foreach ($orders AS $order) {
    $info = array();
    $title = check_plain($order->title);
    if ($order->this_user_purchased) {
      // User bought this ticket.
      $info['status'] = 'The status of your order is \'' . $order->order_status . '\'.';
      if ($order->order_status == 'pending') {
        $info['status'] .= ' Your status will be confirmed after payment has been processed.';
      }
      if ($order->this_user_allocated && $order->qty == 1) {
        $info['attendees'] = '<p>Your ticket is allocated to you. ';
      }
      else {
        $info['attendees'] = count($order->ticket_links) ? t('<p>Current attendees are <ol><li>') . implode('<li>', $order->ticket_links) . '</ol>' : t('<p>No tickets have been allocated.');
      }
      $info['manage'] = t('Click here to ') . l(t('change ticket allocations'), $order->manage_path) . '.';
    }
    elseif ($order->this_user_allocated) {
      // User is just allocated to a ticket.
      $purchaser = user_load(array('uid' => $order->uid));
      $info['status'] = t('<p>Your ticket has been purchased by ') . l($purchaser->name, 'user/' . $purchaser->uid) . '. ' . t('<p>The status of the order is') . ' \'' . $order->order_status . '\'. ';
      if ($order->order_status == 'pending') {
        $info['status'] .= ' Your status will be confirmed after payment has been processed.';
      }
    }
    $output .= '<h4>' . $title . '</h4><p>' . implode(' ', $info) . '</p>';
  }
  if (!$output) {
    $params = array();
    $params['!register'] = l('Buy a ticket', 'register');
    $params['!fullconf'] = l('full conference', 'fullconf');
    $params['!tuesday'] = l('Tuesday', 'tuesday');
    $params['!wednesday'] = l('Wednesday', 'wednesday');
    $params['!thursday'] = l('Thursday', 'thursday');
    $params['!friday'] = l('Friday', 'friday');
    $params['!dinner'] = l('conference dinner', 'dinner');
    $params['!leadership'] = l('leadership forum', 'leadership');

    $output = strtr(variable_get('register_profile_nonreg_blurb', ''), $params);
  }

  return $output;
}

/**
 * Get all orders that the user purchased and the ticket allocation
 * information.
 */
function register_get_orders($uid) {
  // Orders purchased by this user.
  $sql = "
    SELECT uco.order_id, uco.uid, uco.order_status, uco.created, ucop.order_product_id, ucop.nid, ucop.qty, n.title, n.status, n.type
    FROM {uc_orders} uco
    INNER JOIN {uc_order_products} ucop
    ON uco.order_id = ucop.order_id
    INNER JOIN {node} n
    ON n.nid = ucop.nid
    LEFT JOIN {ccc_ticket_allocation} cccta
    ON ucop.order_product_id = cccta.order_product_id
    WHERE (uco.uid = %d OR cccta.uid = %d)
    AND uco.order_status IN ('pending', 'completed', 'payment_received', 'processing')
    AND ucop.nid IN ( " . implode(', ' , register_ticketable_products()) . " )";
  $results = db_query($sql, $uid, $uid); 
  $orders = array();
  while ($row = db_fetch_object($results)) {
    $key = $row->order_id . '.' . $row->order_product_id;
    if (!isset($orders[$key])) {
      $ticket_links = array();
      $ticketholders = register_get_ticketholders($row);
      // Determine some logic flags.
      $row->this_user_allocated = FALSE;
      $row->some_user_allocated = FALSE;
      foreach ($ticketholders AS $ticket) {
        $row->some_user_allocated = TRUE;
        if ($ticket->uid == $uid) {
          $row->this_user_allocated = TRUE;
        }
        // It seems there is not enough ram to display these allocations via theme('username')
        $ticket_links[] = l($ticket->name, 'user/' . $ticket->uid);
      }
      // Can the user reallocate tickets?
      if ($row->uid == $uid) {
        $row->this_user_purchased = TRUE;
        $row->manage_path = 'user/' . $uid . '/tickets/' . $order->order_product_id;
      }
      else {
        $row->manage_path = FALSE;
        $row->this_user_purchased = FALSE;
      }
      // Build the data up for returning.
      $orders[$key] = $row;
      $orders[$key]->tickets = $ticketholders;
      $orders[$key]->ticket_links = $ticket_links;
    }
  }

  return $orders;
}

/**
 * Return a list of users who are allocated tickets on an order.
 * 
 * $order_product
 *   Object that contains ->order_product_id and ->qty and ->uid (purchaser)
 */
function register_get_ticketholders($order_product) {
  $result = db_query("
    SELECT u.uid, u.name, u.mail, u.status, cccta.order_product_id, n.title
    FROM {ccc_ticket_allocation} cccta
    INNER JOIN {users} u
    ON cccta.uid = u.uid
    LEFT JOIN node n
    ON n.uid = cccta.uid AND n.type='profile'
    WHERE cccta.order_product_id = %d
    ", $order_product->order_product_id);
  $ticketholders = array();
  while ($row = db_fetch_object($result)) {
    if ($row->uid) {
      if (!$row->title) {
        // Use the user account name if no profile found.
        $row->title = $row->name;
      }
      $ticketholders[$row->uid] = $row;
    }
  }
  return $ticketholders;
}


/**
 * Display the ticket allocation form
 *
 * TODO: needs a t() cleanup and better for theming?
 */
function register_tickets($user, $order_product_id) {
  return drupal_get_form('register_tickets_form', $user, $order_product_id);
}

function register_tickets_form(&$form_state, $user, $order_product_id = FALSE) {

  $orders = register_get_orders($user->uid);

  $form = array();
  $form['items'] = array('#tree' => TRUE);

  foreach($orders AS $key => $order) {
    $form['items'][$key] = array();
    $form['items'][$key] = array(
      '#type' => 'fieldset',
      '#title' => check_plain($order->title),
      '#collapsible' => TRUE,
      '#collapsed' => ($order_product_id && $order_product_id != $order->order_product_id) ? TRUE : FALSE,
    );
    // $form[$key]['title']['#value'] = '<h2>' . check_plain($order->title) . '</h2>';
    $form['items'][$key]['status']['#value'] = '<p><strong>Order ID:</strong> ' . $order->order_id . '. Status: ' . $order->order_status . '</p>';
    $form['items'][$key]['tickets']['#value'] = '<p><strong>Number of tickets:</strong> ' . $order->qty . '</p>';
    if (!variable_get('ccc_register_allow_prepay_allocation', TRUE) && $order->order_status != 'completed') {
      $form['items'][$key]['warning']['#value'] = '<p class="error">You may not allocate tickets until the order is completed.</p>';      
    }
    else {
      $exist_order_id = register_check_user_allocated_nid($order->nid, $user->uid);
      if ($exist_order_id == $order->order_id) {
        $exist_order_id = FALSE;
      }
      if ((!$order->this_user_allocated && $order->qty == 1) || $order->qty > 1) {
        $form['items'][$key]['alloc_instructions']['#value'] = '<h3>' . t("Ticket Allocation.") . "</h3>\n<p>" . t("Please allocate tickets using a <strong>valid email address</strong> for each user. Click 'Save' when you are done.") . '</p>';
      }
      $form['items'][$key]['order_id'] = array('#type' => 'hidden', '#value' => $order->order_id);
      $form['items'][$key]['order_product_id'] = array('#type' => 'hidden', '#value' => $order->order_product_id);
      $form['items'][$key]['uid'] = array('#type' => 'hidden', '#value' =>  $user->uid);
      $form['items'][$key]['myself'] = array(
        '#type' => 'checkbox',
        '#title'=> $exist_order_id ? 'You are already allocated a ticket under Order #' . $exist_order_id : 'One ticket is allocated to me',
        '#default_value' => $order->this_user_allocated ? TRUE : FALSE,
        '#disabled' => $exist_order_id ? TRUE : FALSE,
      );
      $allocations = $order->tickets;
      ksort($allocations);
      // Don't over allocate if current user is allocated.
      unset($allocations[$user->uid]);
      // And count form elements from 1 instead of 0.
      $start = $order->this_user_allocated ? 2 : 1;
      for ($count = $start; $count <= $order->qty; $count++) {
        $form['items'][$key]['allocations']['rows']['#theme'] = 'register_allocations_form_table';

        $account = array_shift($allocations);
        // Load the user profile, so we can show first name and surname.
        if($account->uid > 0)
          $profile = content_profile_load('profile', $account->uid);
        else
          unset($profile);

        $form['items'][$key]['allocations']['rows'][$count] = array();
        $form['items'][$key]['allocations']['rows'][$count]['remove'] = array(
          '#type' => 'checkbox',
          '#default_value' => FALSE,
          '#disabled' => $account ? FALSE : TRUE,
        );

        $form['items'][$key]['allocations']['rows'][$count]['firstname'] = array(
          '#type' => $account ? 'markup' : 'textfield',
          '#size' => 10,
          '#default_value' => $profile ? $profile->field_profile_firstname[0]['value'] : '',
          '#disabled' => $profile ? TRUE : FALSE,
        );
        if($profile)
          $form['items'][$key]['allocations']['rows'][$count]['firstname']['#value'] = $profile->field_profile_firstname[0]['value'];

        $form['items'][$key]['allocations']['rows'][$count]['surname'] = array(
          '#type' => $account ? 'markup' : 'textfield',
          '#size' => 10,
          '#default_value' => $profile ? $profile->field_profile_surname[0]['value'] : '',
          '#disabled' => $profile ? TRUE : FALSE,
        );
        if($profile)
          $form['items'][$key]['allocations']['rows'][$count]['surname']['#value'] = $profile->field_profile_surname[0]['value'];

        $form['items'][$key]['allocations']['rows'][$count]['position'] = array(
          '#type' => $account ? 'markup' : 'textfield',
          '#size' => 10,
          '#default_value' => $profile ? $profile->field_profile_position[0]['value'] : '',
          '#disabled' => $profile ? TRUE : FALSE,
        );
        if($profile)
          $form['items'][$key]['allocations']['rows'][$count]['position']['#value'] = $profile->field_profile_position[0]['value'];

        $form['items'][$key]['allocations']['rows'][$count]['mail'] = array(
          '#type' => $account ? 'hidden' : 'textfield',
          '#size' => 28,
          '#default_value' => $account ? $account->mail : '',
          '#disabled' => $account ? TRUE : FALSE,
        );

        $form['items'][$key]['allocations']['rows'][$count]['info'] = array(
          '#value' => $account ? l($account->mail, 'user/' . $account->uid) : '',
        );

        // Extra info
        $form['items'][$key]['allocations']['rows'][$count]['uid'] = array('#type' => 'hidden', '#value' => $account->uid);
      }
    }
  }
  
  if (count($orders)) {
    $form['submit'] = array('#type' => 'submit', '#value' => t('Save ticket allocations'));
  } else {
    $params = array();
    $params['!register'] = l('Buy a ticket', 'register');
    $params['!fullconf'] = l('full conference', 'fullconf');
    $params['!tuesday'] = l('Tuesday', 'tuesday');
    $params['!wednesday'] = l('Wednesday', 'wednesday');
    $params['!thursday'] = l('Thursday', 'thursday');
    $params['!friday'] = l('Friday', 'friday');
    $params['!dinner'] = l('conference dinner', 'dinner');
    $params['!leadership'] = l('leadership forum', 'leadership');

    $output = strtr(variable_get('register_no_allocations_blurb', ''), $params);

    $form['items']['none'] = array(
      '#type' => 'markup',
      '#value' => $output,
    );
  }

  return $form;
}

/**
 * Theme a table that is part of register_tickets_form
 */
function theme_register_allocations_form_table(&$element) {
  $titles = array('Remove', 'First name', 'Surname', 'Position', 'Email');
  foreach (element_children($element) AS $cnt) {
    $data[$cnt] = array(
      drupal_render($element[$cnt]['remove']),
      drupal_render($element[$cnt]['firstname']),
      drupal_render($element[$cnt]['surname']),
      drupal_render($element[$cnt]['position']),
      // drupal_render($element[$cnt]['mail']),
      drupal_render($element[$cnt]) );
  }
  $output = theme('table', $titles, $data);
  return $output;
}

function register_tickets_form_validate($form, &$form_state) {
  foreach($form_state['values']['items'] AS $oi => $order) {    
    foreach ($order['allocations']['rows'] AS $ri => $allocated) {
      if (!$allocated['remove'] && !$allocated['uid'] && $allocated['mail']) {
        // New allocation, shouldn't double up.
        $uid = db_result(db_query("SELECT uid FROM users WHERE LCASE(mail) = '%s'", strtolower(trim($allocated['mail']))));
        $order_id = register_check_user_allocated_nid($order->order_product_id, $uid);
        // dpm($uid); dpm($order_id);
        if ($order_id) {
          form_set_error('items][' . $oi . '][allocations][rows][' . $ri . '][mail',  $allocated['mail'] . ' already has a ticket on order #' . $order_id);
        }
      }
    }
  }
  // register_check_user_allocated_nid

  // 1. Check that the user is not allocated on another order
  // 2. Check that the email is valid
}

function register_tickets_form_submit($form, &$form_state) {
  foreach($form_state['values']['items'] AS $order) {

    // Remove all current allocations for this order_product_id.
    //
    $sql = "DELETE FROM {ccc_ticket_allocation} WHERE order_product_id = %d";
    db_query($sql, $order['order_product_id']);

    if ($order['myself']) {
      register_allocate_ticket($order['order_product_id'], $order['uid']);
    }
    foreach ($order['allocations']['rows'] AS $allocated) {
      if (!$allocated['remove'] && ($allocated['uid'] || $allocated['mail'])) {
        $uid = $allocated['uid'] ? $allocated['uid'] : db_result(db_query("SELECT uid FROM users WHERE LCASE(mail) = '%s'", strtolower(trim($allocated['mail']))));
        if ($uid > 0) {
          register_allocate_ticket($order['order_product_id'], $uid);
        } else {
          if(valid_email_address($allocated['mail'])) {
            $new_uid = proposal_copresenter_create(array(
              'mail' => check_plain($allocated['mail']),
              'firstname' => check_plain($allocated['firstname']),
              'surname' => check_plain($allocated['surname']),
              'position' => check_plain($allocated['position'])
            ));
            $allocated[$uid] = $new_uid;
            register_allocate_ticket($order['order_product_id'], $new_uid);
          } else {
            drupal_set_message(t('@email is not a valid email address', array('@email' => $allocated['mail'])), 'error');
          }
        }
      }
    }
  }
  drupal_set_message("Ticket allocations have been saved.");
}

// ------------------------------------------------------------------------------------------
// Short specific API Functions 

/**
 * This returns an order_id of any 1 order (should only ever be one) that a user is allocated to.
 */
function register_check_user_allocated_nid($nid, $uid) {
  $found = db_result(db_query("SELECT ucop.order_id FROM {ccc_ticket_allocation} cccta INNER JOIN {uc_order_products} ucop ON ucop.order_product_id = cccta.order_product_id WHERE ucop.nid = %d AND cccta.uid = %d LIMIT 0, 1", $nid, $uid));
  return $found;
}

/**
 * Alocate a ticket to a user. Make sure we're not overallocating.
 * 
 * This could called on order completion using actions.
 */
function register_allocate_ticket($order_product_id, $uid) {
  // Get the nid and make sure the user is not already allocated to this event.
  $nid = db_result(db_query("SELECT nid FROM uc_order_products WHERE order_product_id = %d", $order_product_id));
  if ($nid && $uid) {
    $found = register_check_user_allocated_nid($nid, $uid);
    $victim = user_load($uid);
    if (!$found) {
      db_query("INSERT INTO {ccc_ticket_allocation} (order_product_id, uid) VALUES (%d, %d)", $order_product_id, $uid);
      register_toggle_attendee_role(&$victim);
      return TRUE;
    } else {
      $ticket = node_load($nid);
      drupal_set_message(t('!username already has a !ticket ticket assigned to them', array('!username' => theme('username', $victim), '!ticket' => $ticket->title)), 'warning');
    }
  }

  return FALSE;
}


// ------------------------------------------------------------------------------------------
// This may be moved to settings and configurations.

/**
 * Variable called 'ccc_register_allow_prepay_allocation'
 */

/**
 * Return a list of valid product IDs
 * 
 * Probably needs an admin screen to choose which nodes are allocatable.
 *
 * Another consideration is to make this funciton only return node types. Which would
 * look attractive if you started getting hundreds of allocatable nids.
 */
function register_ticketable_products() {
  $result = db_query("SELECT nid FROM node WHERE type = 'product' AND status = 1");
  while ($row = db_fetch_array($result)) {
    $nids[$row['nid']] = $row['nid'];
  }
  return $nids;
}

/**
 * Implementation of hook_order() in Übercart.
 *
 * @op		string
 *   operation type.
 * @order	object
 *   containing order info.
 * @a		var
 */
function register_order($op, $order, $a) {
  switch($op) {
    // When saving, store the order id in a session variable.
    // On the thankyou landing page, use this to retrieve the information
    // that is to be stored in the profile.
    // See register_thankyou().
    case 'save':
      $_SESSION['order_id'] = $order->order_id;
      break;
    default:
      break;
  }
}

/**
 * Do some magic to create a user profile if required, then load and display node content from
 * the thankyou story.
 */
function register_thankyou() {

  if(isset($_SESSION['order_id'])) {

    global $user;

    $profile = content_profile_load('profile', $user->uid);
    if(!$profile) {

      // Load orders for this user.
      $order = uc_order_load($_SESSION['order_id']);

      $state = db_result(db_query("SELECT zone_code FROM {uc_zones} WHERE zone_id=%d AND zone_country_id=%d", $order->billing_zone, $order->billing_country));
      $country = db_result(db_query("SELECT country_name country FROM {uc_countries} WHERE country_id=%d", $order->billing_country));

      // Create a profile for the user.
      $profile_attributes = array(
        'nid' => NULL, // NULL creates a new node.
        // 'title' => $new_user->name .'\'s Profile',
        'body' => NULL, // Defaults to no body.
        'type' => 'profile',
        'teaser' => NULL,
        'log' => '',
        'created' => '',
        'format' => FILTER_FORMAT_DEFAULT,
        'uid' => $user->uid,
        'field_profile_firstname' => array(array('value' => ccc_strtot($order->billing_first_name, TRUE))),
        'field_profile_surname' => array(array('value' => ccc_strtot($order->billing_last_name, TRUE))),
        'field_profile_organisation' => array(array('value' => ccc_strtot($order->billing_company, TRUE))),
        'field_profile_phone' => array(array('value' => $order->billing_phone)),
        'field_profile_address' => array(array('value' => $order->billing_street1)),
        'field_profile_city' => array(array('value' => ccc_strtot($order->billing_city))),
        'field_profile_postcode' => array(array('value' => $order->billing_postal_code)),

        'field_profile_state' => array(array('value' => $state)),
        'field_profile_country' => array(array('value' => $country)),
      );

      // Save the profile.
      $new_profile = (object) $profile_attributes;
      node_save($new_profile);

      // Remove the session variable.
      unset($_SESSION['order_id']);
    }
  }

  drupal_goto('thank-you');
}

/**
 * Create and display a table with presenters and whether or not these presenters
 * have registered (and paid) for the day their sessions are scheduled.
 */
function register_list_presenter_payment_status() {

  // Get all presenters (and co-presenters) for all proposals.
  $query = "SELECT
      cfpp.field_proposal_presenters_uid,
      cfpp.delta,
      cfpp.nid,
      ctpr.field_profile_firstname_value,
      ctpr.field_profile_surname_value,
      uc_op.nid AS product_nid,
      uc_op.title AS product_title,
      uc_o.order_id AS order_id,
      uc_os.title AS order_status
    FROM
      {content_field_proposal_presenters} AS cfpp
    JOIN
      {content_type_proposal} AS ctp ON (cfpp.nid = ctp.nid)
    JOIN
      {node} AS n ON (n.uid=cfpp.field_proposal_presenters_uid AND n.type='profile')
    JOIN
      {content_type_profile} AS ctpr ON (n.nid = ctpr.nid)
    LEFT JOIN
      {ccc_ticket_allocation} AS ccc_ta ON (ccc_ta.uid = cfpp.field_proposal_presenters_uid)
    LEFT JOIN
      {uc_order_products} AS uc_op ON (ccc_ta.order_product_id = uc_op.order_product_id)
    LEFT JOIN
      {uc_orders} AS uc_o ON (uc_op.order_id = uc_o.order_id)
    LEFT JOIN
      {uc_order_statuses} AS uc_os ON (uc_o.order_status = uc_os.order_status_id)
    WHERE
      ctp.field_proposal_status_value IN('accepted', 'accepted with minor changes')
    ORDER BY
      ctpr.field_profile_surname_value ASC, ctpr.field_profile_firstname_value ASC
      ";

  $result = db_query($query);

  while ($o = db_fetch_object($result)) {
    if (!count($tix)) {
      $tix = array('Not registered yet.');
    }

    $tuple = array(
      'nid' => l($o->nid, 'node/'. $o->nid),
      'firstname' => $o->field_profile_firstname_value,
      'surname' => $o->field_profile_surname_value,
      'type' => ($o->delta == 0) ? 'Primary' : ordinalise($o->delta) . ' Co',
      'status' => ($o->order_status) ? l($o->order_status, 'admin/store/orders/' . $o->order_id) : '',
      'product' => $o->product_title,
    );
    $data[] = $tuple;
  }

  $output  = t('<h3>Found !num records</h3>', array('!num' => count($data)));
  $output .= t('<p>Note that a presenter will be listed once for each product in their order and more often if they are both a primary presenter for one or more sessions and a co-presenter for one or more other sessions.</p>');
  $output .= t('<p>Session schedule information is not yet available within the system.</p>');


  $headers = array('Proposal','Firstname','Surname','Type','Status','Product');

  $output .= theme('table', $headers, $data);
  return $output;
}

/**
 * Display couon codes used and the orders they wered used on.
 */
function register_list_coupon_status() {
  $query = "
    SELECT
      uc_co.oid AS order_id,
      uc_o.uid AS uid,
      ctp.field_profile_firstname_value AS firstname,
      ctp.field_profile_surname_value AS surname,
      uc_o.created AS order_date,
      uc_os.title AS order_status,
      uc_o.order_total AS order_total,
      uc_co.code AS coupon
    FROM
      {uc_coupons_orders} AS uc_co
    JOIN
      {uc_orders} AS uc_o ON (uc_o.order_id=uc_co.oid)
    JOIN
      {uc_order_statuses} AS uc_os ON (uc_o.order_status = uc_os.order_status_id)
    JOIN
      {node} AS n ON (n.uid=uc_o.uid AND n.type='profile')
    JOIN
      {content_type_profile} AS ctp ON (ctp.nid=n.nid)
    WHERE
      uc_o.order_status IN ('" . implode("', '", sessions_valid_order()) . "')
    ";

  $header = array(
    array('data' => t('User'),   'field' => 'ctp.field_profile_surname_value'),
    array('data' => t('Order'),  'field' => 'uc_o.order_id'),
    array('data' => t('Status'), 'field' => 'uc_os.title'),
    array('data' => t('Total'),  'field' => 'uc_o.order_total'),
    array('data' => t('Date'),   'field' => 'uc_o.created'),
    array('data' => t('Coupon')  'field' => 'uc_co.code'),
  );

  $query .= tablesort_sql($header);
  $result = db_query($query);

  while ($o = db_fetch_object($result)) {
    $tuple = array(
      'user' => ($o->uid) ? l($o->firstname . ' ' . $o->surname, 'user/' . $o->uid) : ($o->firstname . ' ' . $o->surname),
      'oid' => l($o->order_id, 'admin/store/orders/' . $o->order_id),
      'status' => $o->order_status,
      'total' => $o->order_total,
      'date' => strftime('%Y-%m-%d %H:%M', $o->order_date),
      'code' => $o->coupon,
    );
    $data[] = $tuple;
  }


  $suffix = (count($data) != 1) ? t('s') : t('');
  $verb = (count($data) != 1) ? t('have') : t('has');
  $output  = t('<h3>!num Coupon!s !verb been used</h3>', array('!num' => count($data), '!s' => $suffix, '!verb' => $verb));

  $output .= theme('table', $header, $data);

  return $output;
}

/**
 * Return a random list of registrees
 */
function register_prizedraw() {

  // Get all users who have a completed or payment received ticket allocated to them.
  $query = "SELECT
      ccc_ta.uid AS uid,
      uc_op.order_id AS order_id,
      uc_op.order_product_id,
      uc_o.order_status AS order_status,
      n.title,
      ctp.field_profile_firstname_value AS firstname,
      ctp.field_profile_surname_value AS surname
    FROM
      {uc_order_products} AS uc_op
    JOIN
      {uc_orders} AS uc_o ON (uc_op.order_id = uc_o.order_id)
    JOIN
      {ccc_ticket_allocation} AS ccc_ta ON (ccc_ta.order_product_id=uc_op.order_product_id)
    JOIN
      {node} AS n ON (uc_op.nid=n.nid)
    LEFT JOIN
      {node} AS np ON (ccc_ta.uid=np.uid AND np.type='profile')
    LEFT JOIN
      {content_type_profile} AS ctp ON(np.nid=ctp.nid)
    WHERE
      uc_o.order_status IN ('completed','payment_received')
    GROUP BY
      ccc_ta.uid
    ORDER BY
      RAND()
    LIMIT
      10";

  $result = db_query($query);

  while ($o = db_fetch_object($result)) {
    $tuple = array(
      'user' => ($o->uid) ? l($o->firstname . ' ' . $o->surname, 'user/' . $o->uid) : ($o->firstname . ' ' . $o->surname),
      'oid' => l($o->order_id, 'admin/store/orders/' . $o->order_id),
      'order' => $o->title,
      'status' => $o->order_status,
    );
    $data[] = $tuple;
  }

  $headers = array('Name', 'Order', 'Product', 'Status');

  $output  = t('<p>Here are 10 random people with tickets from a completed or paid order allocated to them.');
  $output .= theme('table', $headers, $data);

  return $output;
}

/**
 * Filter form for the attendee listing.
 */
function register_product_filter_form($form_state) {
  // Create a keyed array of products.
  //
  $options = array(0 => 'List all');
  $result = db_query("SELECT nid,title FROM {node} WHERE type = 'product'");
  while ($o = db_fetch_object($result)) {
    $options[$o->nid] = $o->title;
  }

  $form = array();
  $form['filter'] = array(
    '#title' => 'Filter',
    '#type' => 'fieldset',
    '#description' => 'Choose a product to filter the results by.',
  );
  $form['filter']['product'] = array(
    '#title' => 'Product',
    '#type' => 'select',
    '#options' => $options,
  );
  $form['filter']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Filter',
  );
}

/**
 * List all users with a ticket of some kind allocated to them.
 */
function register_list_attendees() {

  $count_query = "SELECT
      COUNT(DISTINCT(ccc_ta.uid))
    FROM
      {uc_order_products} AS uc_op
    JOIN
      {uc_orders} AS uc_o ON (uc_op.order_id = uc_o.order_id)
    JOIN
      {ccc_ticket_allocation} AS ccc_ta ON (ccc_ta.order_product_id=uc_op.order_product_id)
    JOIN
      {node} AS n ON (uc_op.nid=n.nid)
    WHERE
      uc_o.order_status IN ('" . implode("', '", sessions_valid_order()) . "')";

  $select_query = "SELECT
      ccc_ta.uid AS uid,
      uc_op.order_id AS order_id,
      uc_op.order_product_id,
      uc_o.order_status AS order_status,
      n.title,
      ctp.field_profile_firstname_value AS firstname,
      ctp.field_profile_surname_value AS surname
    FROM
      {uc_order_products} AS uc_op
    JOIN
      {uc_orders} AS uc_o ON (uc_op.order_id = uc_o.order_id)
    JOIN
      {ccc_ticket_allocation} AS ccc_ta ON (ccc_ta.order_product_id=uc_op.order_product_id)
    JOIN
      {users} AS u ON (u.uid = ccc_ta.uid)
    JOIN
      {node} AS n ON (uc_op.nid=n.nid)
    LEFT JOIN
      {node} AS np ON (ccc_ta.uid=np.uid AND np.type='profile')
    LEFT JOIN
      {content_type_profile} AS ctp ON(np.nid=ctp.nid)
    WHERE
      uc_o.order_status IN ('" . implode("', '", sessions_valid_order()) . "')
    GROUP BY
      ccc_ta.uid
    ORDER BY
      ctp.field_profile_surname_value ASC,
      ctp.field_profile_firstname_value ASC";

  $items_per_page = 20;
  $total = db_result(db_query($count_query));
  $page = intval($_REQUEST['page']);

  $select_query = db_rewrite_sql($select_query);
  $result = pager_query($select_query, $items_per_page, 0, $count_query);

  while ($o = db_fetch_object($result)) {
    $tuple = array(
      'user' => ($o->firstname) ? l($o->firstname . ' ' . $o->surname, 'user/' . $o->uid) : l($o->username, 'user/'. $o->uid),
      'oid' => l($o->order_id, 'admin/store/orders/' . $o->order_id),
      'order' => $o->title,
      'status' => $o->order_status,
    );
    $data[] = $tuple;
  }

  $headers = array('Name', 'Order', 'Product', 'Status');

  drupal_set_title('Attendee Report');
  $output .= t('Listing !start - !end of !total attendees who have a ticket of any kind allocated to them.',
    array(
      '!start' => ($items_per_page * $page) + 1,
      '!end' => min($total, ($items_per_page * ($page + 1))),
      '!total' => $total,
    ));
  $output .= drupal_get_form('register_product_filter');
  $output .= theme('table', $headers, $data);
  $output .= theme('pager', array(), $items_per_page);

  return $output;
}

/**
 * Provide an overview of various registration numbers.
 */
function register_list_overview() {

  if (!module_exists("sessions")) {
    return t('The sessions module is required for these reports.');
  }

  $output = '';

  // Number of distinct users with a ticket of any kind allocated to them.
  //
  $attendees = db_result(db_query("SELECT COUNT(DISTINCT(uid)) FROM {ccc_ticket_allocation}"));
  $output .= '<h3>Overview</h3>';
  $output .= t('<p>There are !num distinct people who have a ticket of any kind allocated to them', array('!num' => $attendees));
  $output .= '<hr size="1" />';

  // Number of people with each ticket type.
  //
  $data = array();
  $query = "SELECT DISTINCT(op.nid) AS nid, op.title AS ticket, SUM(op.qty) AS sold FROM {uc_order_products} AS op LEFT JOIN {uc_orders} AS o ON (o.order_id=op.order_id) WHERE o.order_status IN ('" . implode("', '", sessions_valid_order()) . "') GROUP BY op.nid";
  $result = db_query($query);

  while($row = db_fetch_array($result)) {
    unset($row['nid']);
    $data[] = $row;
  }
  $output .= '<h3>Tickets Sold</h3>';
  $output .= theme('table', array('Ticket', 'Sold Qty'), $data);
  $output .= '<hr size="1" />';

  // Allocated tickets.
  //
  $data = array();
  $query = "SELECT DISTINCT(uc_op.nid) AS nid, uc_op.title AS title, COUNT(ccc_ta.uid) AS allocated FROM {uc_order_products} AS uc_op JOIN {ccc_ticket_allocation} AS ccc_ta ON (uc_op.order_product_id = ccc_ta.order_product_id) GROUP BY uc_op.nid";
  $result = db_query($query);

  while($row = db_fetch_array($result)) {
    unset($row['nid']);
    $data[] = $row;
  }
  $output .= '<h3>Tickets Allocated</h3>';
  $output .= theme('table', array('Ticket', 'Allocated Qty'), $data);
  $output .= '<hr size="1" />';

  // Total number of presenters.
  //
  $data = array();

  $presenters_total = db_result(db_query("SELECT COUNT(DISTINCT(field_proposal_presenters_uid)) AS num FROM {content_field_proposal_presenters} AS cfpp
LEFT JOIN {content_type_proposal} AS ctp ON (ctp.nid = cfpp.nid) WHERE ctp.field_proposal_status_value IN ('" . implode("','", sessions_valid_status()) . "')"));
  $data[] = array(
    'Total presenters',
    $presenters_total,
    100
  );

  // Presenters who have an allocated ticket.
  //
  $presenters_ticket = db_result(db_query("SELECT COUNT(DISTINCT(cfpp.field_proposal_presenters_uid)) AS num FROM {content_field_proposal_presenters} AS cfpp JOIN {ccc_ticket_allocation} AS ccc_ta ON (cfpp.field_proposal_presenters_uid = ccc_ta.uid)
LEFT JOIN {content_type_proposal} AS ctp ON (ctp.nid = cfpp.nid) WHERE ctp.field_proposal_status_value IN ('" . implode("','", sessions_valid_status()) . "')"));
  $data[] = array(
    'Presenters with allocated ticket',
    $presenters_ticket,
    sprintf("%0.1f", ($presenters_ticket / $presenters_total) * 100)
  );

  // Presenters who do not have an allocated ticket.
  //
  $presenters_noticket = db_result(db_query("SELECT COUNT(DISTINCT(cfpp.field_proposal_presenters_uid)) AS num FROM {content_field_proposal_presenters} AS cfpp
LEFT JOIN {content_type_proposal} AS ctp ON (ctp.nid = cfpp.nid) WHERE ctp.field_proposal_status_value IN ('" . implode("','", sessions_valid_status()) . "')
AND cfpp.field_proposal_presenters_uid NOT IN (SELECT uid FROM {ccc_ticket_allocation})"));
  $data[] = array(
    'Presenters without allocated ticket',
    $presenters_noticket,
    sprintf("%0.1f", ($presenters_noticket / $presenters_total) * 100)
  );

  $output .= '<h3>Presenter Registration Info</h3>';
  $output .= theme('table', array('Presenters', 'Number', 'Percentage'), $data);
  $output .= t('<p><em>Note that these numbers reflect presenters and co-presenters whose proposals are listed as <strong>accepted</strong> and who have an <string>allocated</strong> ticket. We cannot limit this to presenters who have bought a ticket, as their ticket may be purchased for them by a third party. This means presenters who purchased their own ticket, but did not allocate it to themselves are counted here as not having a ticket.</em>');

  drupal_set_title('Registration Overview');
  return $output;
}

function ordinalise($number) {
  if (in_array(($number % 100),range(11,13))){
    return $number.'th';
  } else {
    switch (($number % 10)) {
     case 1:
      return $number.'st';
      break;
    case 2:
      return $number.'nd';
      break;
    case 3:
      return $number.'rd';
    break;
    default:
      return $number.'th';
      break;
    }
  }
}

/**
 * Obtain a number of "products" that are assigned to this user.
 *
 * @uid
 *   An integer referring to a user.
 */
function register_get_tickets($uid) {
  $query = "SELECT DISTINCT(uc_op.nid), n.title FROM {uc_order_products} AS uc_op JOIN 
    {ccc_ticket_allocation} AS cccta ON (uc_op.order_product_id = cccta.order_product_id)
    JOIN {node} AS n ON (uc_op.nid = n.nid)
    WHERE cccta.uid=%d";
  $result = db_query($query, $uid);
  while ($o = db_fetch_object($result)) {
    $data[] = $o;
  }
  return $data;
}

// Skeleton code for mailmerge.
//
// Presenters who haven't registered
//   (proposal accepted and uid in proposal_presenters and not in uc_orders and not in ccc_ticket_allocation)
// Presenters who have registered, but not allocated their ticket
//   (proposal accepted and uid in proposal_presenters and in uc_orders and not in ccc_ticket_allocation)
// Presenters who have registered and allocated their ticket, but have not selected sessions
//   (proposal accepted and uid in proposal_presenters and in ccc_ticket_allocation and not in ccc_session_selection)
// Users whose order hasn't had its tickets allocated yet
//   (order_product_id not in ccc_ticket_allocation)
// Users who haven't got a ticket allocated to them
//   (uid not in ccc_ticket_allocation)
// Users who have got a ticket allocated to them
//   (uid in ccc_ticket_allocation)
// Users with tickets who haven't selected sessions yet
//   (uid in ccc_ticket_allocation and not in ccc_session_selection)
// Users with tickets who have selected sessions
//   (uid in ccc_ticket_allocation and in ccc_session_selection)
// Users with accessibility or dietary needs
//   (data in content_type_profile fields)

// u.uid, u.mail, pro.firstname, pro.surname
//   proposal, scheduled
//   link to pro
//   link to ccc_ta
//   link to ccc_ss

