<?php
/**
 * Implements hook_install()
 */
function register_install() {
  register_update_6100();
}

/**
 * Implements hook_update_N()
 *
 * Make sure we run AFTER uc_signup. This is needed for hook_order().
 */
function register_update_6100() {
  $weight = db_result(db_query("SELECT weight FROM {system} WHERE name = 'uc_signup'"));
  db_query("UPDATE {system} SET weight = %d WHERE name = 'register'", ++$weight);
}
